MTL-1718: Add prune stage to daily build.
Cray-HPE/node-images pull request #280
Opened 2022-05-11 14:49 UTC by manderson-hpe

#### Summary and Scope

- Relates to [MTL-1668](https://github.com/Cray-HPE/csm-shared-library/pull/27)

##### Issue Type

- RFE Pull Request

This change adds the prune stage for daily execution. Pruning will remove all unstable images that are older than the most current release.

This stage was in previous build but was removed during the transition to GitHub. It is now being added back along with the release code for GCP.

2022-05-13 04:29 UTC, rustydb requested changes
Holding until csm-shared-library is pointed at main.

2022-05-13 04:29 UTC, rustydb commented on Jenkinsfile.github
> +@Library('csm-shared-library@MTL-1668') _
Just need to switch back to main.

2022-05-13 04:29 UTC, rustydb commented on Jenkinsfile.github
> +@Library('csm-shared-library@MTL-1668') _
I think that merged already.. if not then obviously we'll wait for that to merge first.

2022-07-05 14:22 UTC, rustydb commented
Rebased and resolved conflict.

2022-08-16 16:13 UTC, rustydb commented
pit-common was renamed to pre-install-toolkit for 1.3 (lts/csm-1.3) and 1.4 (main), but pit-common still exists for lts/csm-1.2. We probably want to prune all pit-common, and also search for pre-install-toolkit.

NOTE That the cray-pre-install-toolkit directory still exists in Artifactory until we get an ISO built from this repo.

2022-09-21 19:04 UTC, rustydb commented on Jenkinsfile.github
> +def prune = true
```suggestion
def doPrune = true
```

2022-09-21 19:04 UTC, rustydb commented on Jenkinsfile.github
> +        booleanParam(name: 'prune', defaultValue: prune, description: 'Whether or not to prune all images older than the latest release timestamp.')
```suggestion
        booleanParam(name: 'prune', defaultValue: doPrune, description: 'Whether or not to prune all images older than the latest release timestamp.')
```

2022-09-21 19:04 UTC, rustydb commented on Jenkinsfile.github
> +            0 6 * * * %prune=true
```suggestion
            0 6 * * * %doPrune=true
```

2022-09-22 20:37 UTC, rustydb requested changes

2022-09-22 20:37 UTC, rustydb commented on Jenkinsfile.github
> +            when { expression { params.prune } }
Would also run this exclusively, and not when as part of a users build.
```suggestion
            when {
                expression { params.prune }
                expression { !params.buildAndPublish }
            }
```

2022-09-22 20:37 UTC, rustydb commented on Jenkinsfile.github
> +            when { expression { params.prune } }
Then to each stage add this to prevent them from running anything when a prune is running.
```groovy
            when {
                expression { !params.prune }
            }
```

So add it to:
- `setup`
- `base layer(s)`
- `common layer(s)`
- `ncn node layers`

2022-09-22 22:52 UTC, rustydb commented on Jenkinsfile.github
> +            when { expression { params.prune } }
Basically need to make this pipeline not run anything else except the prune stage when pruning.
As well as never run the prune stage when not pruning.

2022-09-23 13:12 UTC, manderson-hpe commented on Jenkinsfile.github
> +            when { expression { params.prune } }
Also needs to be on the `post('Test Results')` step as well, right?

2022-09-23 15:02 UTC, rustydb requested changes

2022-09-24 06:48 UTC, rustydb commented on Jenkinsfile.github
> +            when { expression { params.prune } }
Yup
https://github.com/Cray-HPE/node-images/pull/280#discussion_r978774540

2022-09-26 16:16 UTC, rustydb approved these changes

2022-09-27 02:42 UTC, rustydb commented
/fast-forward

2022-09-27 02:42 UTC, rustydb commented
Fast-forward Succeeded!

2022-09-27 02:42 UTC, merged