VSHA-420 - Add goss tests to pit, ceph and kubernetes images
Cray-HPE/node-images pull request #429
Opened 2022-08-05 15:14 UTC by wiltonpaulo

### Summary and Scope

- Fixes:
- Requires:
- Relates to:

#### Issue Type

- Bugfix Pull Request
- Docs Pull Request
- RFE Pull Request

### Prerequisites

- [ ] I have included documentation in my PR (or it is not required)
- [ ] I tested this on internal system (if yes, please include results or a description of the test)
- [ ] I tested this on a vshasta system (if yes, please include results or a description of the test)
 
### Idempotency
 

 
### Risks and Mitigations

2022-08-05 17:03 UTC, rustydb requested changes

2022-08-05 17:03 UTC, rustydb commented on Jenkinsfile.github
> +        // This step gets all goss tests results
Can this step be removed?

Each build will emit failures at the end since we run the tests in the packer build.

Only reason why I ask for this to be removed really is that in my vagrant branch the Jenkinsfile is about 10 characters short from being too large. Trying to keep the Jenkinsfile smaller if possible. Since this step is already accounted for in the packer builds themselves it seems a little redundant.

2022-08-05 17:24 UTC, wiltonpaulo commented on Jenkinsfile.github
> +        // This step gets all goss tests results
Sure, I didn't know about this vagrant limit. Is that ok if only left the junit recording the tests?

2022-08-05 19:13 UTC, rustydb commented on Jenkinsfile.github
> +        // This step gets all goss tests results
I do see that this would've added a graph in Jenkins, which would've been neat. 
![image](https://user-images.githubusercontent.com/7772179/183145389-48f8f3e3-6678-42a5-a155-8b9d776dff37.png)
Is there a way we can do that without this Jenkins step?

2022-08-05 19:27 UTC, wiltonpaulo commented on Jenkinsfile.github
> +        // This step gets all goss tests results
I'd like to add this test step because there is a request to integrate the builds with the livecd vshasta v2 tests (I'll work on that too: VSHA-422).

2022-08-07 20:08 UTC, rustydb commented
Rebased.

2022-08-09 20:08 UTC, rustydb commented
Merging this after #435 and after #433 .

2022-08-09 20:09 UTC, rustydb approved these changes

2022-08-09 23:38 UTC, merged

2022-08-10 00:02 UTC, rustydb commented
I had to back this out. The newly added stage needs the same `when` statement that the other build stages have so that tests are only collected when builds are done.

```groovy
            when {
                expression { env.TAG_NAME == null && (!(BRANCH_NAME ==~ promotionToken) || (BRANCH_NAME ==~ promotionToken && params.buildAndPublish)) }
            }
```