VSHA-436 - Add last build artifact version from commit
Cray-HPE/node-images pull request #493
Opened 2022-09-13 14:19 UTC by wiltonpaulo

### Summary and Scope

- Relates to: VSHA-436, VSHA-424, VSHA-442

The node-images build branch will be able to pass parameters and trigger steps to test in the LiveCD pipeline.

#### Issue Type

- Improve test by implementing a new livecd test layer
- Add a code block to trigger the liveCD test infrastructure job.
https://jenkins.algol60.net/job/Cray-HPE/job/livecd-gcp-infrastructure/

When builds are complete the build pipeline should automatically test those images
The image should be launched, and Goss tests should be run to validate the image contents.

### Prerequisites

- [x] I have included documentation in my PR (or it is not required)
- [x] I tested this on internal system (if yes, please include results or a description of the test)
- [x] I tested this on a vshasta v2 system (if yes, please include results or a description of the test)
 
### Idempotency
 

 
### Risks and Mitigations

2022-09-13 17:10 UTC, rustydb requested changes

2022-09-13 17:10 UTC, rustydb commented on Jenkinsfile.github
> +        stage('Pre-Start') {
Can this move into the Setup stage?
I think the `sh 'echo ${COMMIT_VERSION}'` already happens.. when the `setImageVersion is ran. Maybe `getCommitImageVersion` can also echo this instead of having to echo it separately here?

2022-09-13 17:17 UTC, wiltonpaulo commented on Jenkinsfile.github
> +        stage('Pre-Start') {
Sorry. The PR is not ready yet. I was just testing.

2022-09-13 21:48 UTC, rustydb commented on Jenkinsfile.github
> +        COMMIT_VERSION = getImageVersion(commitHashShort: GIT_COMMIT[0..6])
Will this ever fail or cause a problem if a version doesn't exist?
For example on a feature branch?

2022-09-13 22:27 UTC, wiltonpaulo commented on Jenkinsfile.github
> +        COMMIT_VERSION = getImageVersion(commitHashShort: GIT_COMMIT[0..6])
It will return a "null" value if no version is found. I did this test on this "temp pipeline"
https://jenkins.algol60.net/job/node-image-version-test/

2022-09-14 00:49 UTC, wiltonpaulo commented on Jenkinsfile.github
> +        COMMIT_VERSION = getImageVersion(commitHashShort: GIT_COMMIT[0..6])
Moved to the build trigger section.

2022-09-14 13:05 UTC, rustydb approved these changes

2022-09-14 13:08 UTC, rustydb commented
/fast-forward

2022-09-14 13:08 UTC, rustydb commented
Fast-forward Succeeded!

2022-09-14 13:08 UTC, merged